<?php
/**
 * The copy-paste brief that lets an AI agent design a promo template.
 *
 * @since 1.3.0
 * @package WhimsicalPromo
 */

namespace WhimsicalPromo;

/**
 * Class Agent_Brief
 *
 * Everything an agent needs to produce a new design without reading this codebase:
 * the markup it may not change, the vocabulary of classes it can hook onto, the
 * custom properties the editor can override, and one complete worked example.
 *
 * The brief itself is deliberately untranslated. It is a technical payload handed to
 * a machine — the same category as the CSS templates — and the labels around it in
 * the meta box carry the localisation.
 *
 * @since   1.3.0
 * @package WhimsicalPromo
 */
class Agent_Brief {

	/**
	 * The whole brief for one promo, ready to paste into an agent.
	 *
	 * @param int $post_id Promo ID.
	 *
	 * @return string
	 */
	public static function text( int $post_id ): string {
		// The placeholder, not this promo's real id: the plugin rewrites it per promo on
		// output, so a brief carrying a concrete id would teach it as part of the
		// contract and make the rewrite look like magic when the CSS is pasted elsewhere.
		$wrapper = '#whim-promo-' . Styles::ID_PLACEHOLDER;
		$slug    = Styles::slug_for( $post_id );

		$sections = [
			self::goal( $wrapper ),
			self::markup( $wrapper ),
			self::vocabulary(),
			self::body_shapes(),
			self::tokens(),
			self::motion( $wrapper ),
			self::rules( $wrapper ),
			self::example( $slug ),
			self::deliverable( $wrapper ),
		];

		return implode( "\n\n", $sections ) . "\n";
	}

	/**
	 * What the agent is being asked for.
	 *
	 * @param string $wrapper This promo's id selector.
	 *
	 * @return string
	 */
	protected static function goal( string $wrapper ): string {
		return implode(
			"\n",
			[
				'# Design a promo template',
				'',
				'You are designing the look of one promo on a WordPress news site. A promo is a',
				'small card that either sits inline in an article or appears over it on exit',
				'intent. The markup is fixed and generated by a plugin — you cannot add, remove',
				'or reorder elements. Your job is the CSS, plus a sample body that shows it off.',
				'',
				'Return exactly two code blocks, in this order:',
				'',
				'1. `html` — a sample promo body, to paste into the WordPress block editor.',
				'2. `css` — one stylesheet, to paste into the promo\'s Custom CSS field.',
				'',
				'Every selector in the CSS must begin with `' . $wrapper . '`, written with the',
				'literal word `' . Styles::ID_PLACEHOLDER . '`. The plugin swaps that for the',
				'promo\'s own post id when it renders, which is what keeps each design scoped to',
				'its own promo and ahead of the plugin\'s base styles. Do not use `!important` —',
				'you never need it.',
			]
		);
	}

	/**
	 * The DOM the plugin emits.
	 *
	 * @param string $wrapper This promo's id selector.
	 *
	 * @return string
	 */
	protected static function markup( string $wrapper ): string {
		$id = ltrim( $wrapper, '#' );

		return implode(
			"\n",
			[
				'## The markup you are styling',
				'',
				'Inline placement:',
				'',
				'```html',
				'<div class="whim-promo-slot has-promo">',
				'  <div id="' . $id . '" class="whim-promo whim-promo--inline-hook',
				'       whim-promo--preset-slide-up-spring whim-promo--style-your-slug" hidden',
				'       data-whim-slug="…" data-whim-placement="inline_hook" data-whim-preset="…">',
				'    <div class="whim-promo__card">',
				'      <div class="whim-promo__body"><!-- editor content --></div>',
				'    </div>',
				'  </div>',
				'</div>',
				'```',
				'',
				'Exit intent adds a backdrop (modal only), dialog semantics on the card, and a',
				'dismiss button that is last in the card so the first Tab reaches the call to',
				'action instead of the close control:',
				'',
				'```html',
				'<div id="' . $id . '" class="whim-promo whim-promo--exit-intent',
				'     whim-promo--preset-slide-up-spring whim-promo--style-your-slug',
				'     whim-promo--modal" hidden data-whim-presentation="modal">',
				'  <div class="whim-promo__backdrop" data-whim-close="1"></div>',
				'  <div class="whim-promo__card" role="dialog" tabindex="-1" aria-modal="true"',
				'       aria-label="Promo title">',
				'    <div class="whim-promo__body"><!-- editor content --></div>',
				'    <button type="button" class="whim-promo__close" data-whim-close="1"',
				'            aria-label="Dismiss">&times;</button>',
				'  </div>',
				'</div>',
				'```',
				'',
				'That is the whole skeleton. Ornament goes on `::before` / `::after` of these',
				'elements — there is nowhere else to put it.',
			]
		);
	}

	/**
	 * The classes and states a template may hook onto.
	 *
	 * @return string
	 */
	protected static function vocabulary(): string {
		return implode(
			"\n",
			[
				'## Classes you can hook onto',
				'',
				'Placement, always exactly one:',
				'',
				'- `.whim-promo--inline-hook` — sits in the article flow, in normal document order.',
				'- `.whim-promo--exit-intent` — `position: fixed`, shown when the reader looks',
				'  like they are leaving.',
				'',
				'Presentation, exit intent only, exactly one:',
				'',
				'- `.whim-promo--modal` — centred over the page, with the backdrop element.',
				'- `.whim-promo--slide-down` — pinned to the top edge, no backdrop.',
				'- `.whim-promo--slide-up` — pinned to the bottom edge, no backdrop.',
				'',
				'Entry preset, always exactly one — the editor picks it per promo, so all four',
				'need to look deliberate in your design:',
				'',
				'- `.whim-promo--preset-slide-up-spring` — rises into place with a slight overshoot.',
				'- `.whim-promo--preset-slide-down-spring` — the same, travelling downward. Pair it',
				'  with a top-edge bar.',
				'- `.whim-promo--preset-fade-rise` — a soft fade and short lift, no overshoot.',
				'- `.whim-promo--preset-none` — no movement; the fade the base stylesheet owns still',
				'  applies.',
				'',
				'States, added and removed by the plugin\'s script:',
				'',
				'- `[hidden]` — before the promo is allowed to show. The plugin removes it.',
				'- `.is-revealed` — on the wrapper once the promo is live. This is the resting',
				'  state: everything your entry animation moves must come back to rest here.',
				'- `.is-lit` — on the wrapper for accent details, on a beat of its own: as the',
				'  card crosses the middle of the viewport when inline, with the entrance when it',
				'  opens over the page.',
				'- `.is-dismissing` — on the wrapper while it bows out. Style the exit here.',
				'- `.is-clicked` — briefly on a call to action that was just clicked, for a',
				'  click flourish.',
			]
		);
	}

	/**
	 * What the editor-authored body can contain.
	 *
	 * @return string
	 */
	protected static function body_shapes(): string {
		return implode(
			"\n",
			[
				'## What is inside `.whim-promo__body`',
				'',
				'An editor writes this in WordPress, so it is ordinary prose markup: `h2`–`h4`,',
				'`p`, `ul`/`ol`, `a`, `img`, and sometimes a shortcode form. Style all of it.',
				'',
				'The plugin adds one class before rendering: any paragraph whose entire content',
				'is a single link gets `whim-cta` on that link. So these all need a button look:',
				'',
				'- `a.whim-cta` — the standard call to action.',
				'- `a.whim-cta.whim-btn--google` — "Add as a preferred source on Google". Google\'s',
				'  brand rules want a white chip with dark text and the multicolour G to the left of',
				'  the label, whatever your card background is. Draw the G as an inline `data:` URI',
				'  `::before` so it needs no network request and passes a strict CSP.',
				'- `a.whim-cta:has(> img:only-child)` — a link wrapping only an image. Treat it as',
				'  artwork on a backing plate: no button chrome, no padding pretending to be a pill.',
				'- `.wp-block-button__link` — the same button, from the core Buttons block.',
				'- `button`, `input[type="submit"]` — a form\'s own controls.',
				'- `a.whim-link` — an opt-out: a standalone link the editor wants left as text.',
				'',
				'A link inside a sentence must never look like a button; give it a text-link',
				'treatment. Do not try to tell the two cases apart in CSS — `p > a:only-child`',
				'matches both, because text nodes are not children. The plugin has already made',
				'that decision for you with `whim-cta`.',
			]
		);
	}

	/**
	 * The custom properties the editor can override per promo.
	 *
	 * @return string
	 */
	protected static function tokens(): string {
		$lines = [
			'## Custom properties the editor can override',
			'',
			'Each promo has fields that write these onto the wrapper as an inline `style`',
			'attribute. Define them in your stylesheet and *consume them everywhere*, so those',
			'fields keep working:',
			'',
		];

		foreach ( Post_Type::STYLE_TOKENS as $token ) {
			$lines[] = '- `--whim-' . $token . '`';
		}

		$lines[] = '';
		$lines[] = 'Also honoured by the base stylesheet, so keep the names:';
		$lines[] = '';
		$lines[] = '- `--whim-max-width` — the card\'s `max-inline-size`. Set it per presentation.';
		$lines[] = '- `--whim-duration`, `--whim-ease` — entry and exit timing.';
		$lines[] = '';
		$lines[] = 'The card is `container-type: inline-size`, so use container queries (`cqi`,';
		$lines[] = '`@container`) rather than viewport queries to adapt the layout — the same card';
		$lines[] = 'renders full-bleed as a bar and narrow as a modal.';

		return implode( "\n", $lines );
	}

	/**
	 * How the reveal works, and the two rules a template must not break.
	 *
	 * @param string $wrapper This promo's id selector.
	 *
	 * @return string
	 */
	protected static function motion( string $wrapper ): string {
		return implode(
			"\n",
			[
				'## How the reveal works',
				'',
				'The base stylesheet owns the fade and you do not restate it:',
				'',
				'```css',
				'.whim-promo .whim-promo__card            { opacity: 0 }',
				'.whim-promo.is-revealed .whim-promo__card { opacity: 1 }',
				'```',
				'',
				'Your template adds movement on top. Two hard requirements:',
				'',
				'1. **Wrap every entry offset in `:where()`.** An offset written flat, as',
				'   `' . $wrapper . '.whim-promo--slide-down .whim-promo__card`, scores the same as',
				'   the `' . $wrapper . '.is-revealed .whim-promo__card` reset — so source order',
				'   decides which wins, and the card can stay parked off screen forever. Written as',
				'   `' . $wrapper . ':where(.whim-promo--slide-down) .whim-promo__card` it scores',
				'   lower than the reset, and the card always settles.',
				'2. **Reset everything you moved under `.is-revealed`.** Whatever properties your',
				'   offsets touch, set them back to rest there.',
				'',
				'Animate only compositor-friendly properties: `translate` / `scale` / `rotate` (or',
				'`transform`), `opacity` and `filter`. Nothing that triggers layout.',
				'',
				'There is a second state class, `.is-lit`, for accent details — a rule, a glow, a',
				'flourish — so they get their own beat instead of arriving with the card. An',
				'inline promo is lit as its middle crosses the middle of the viewport; a promo',
				'that opens over the page is lit with its entrance. Rest state on the element,',
				'end state under `.is-lit`, and a delay if you want the stagger:',
				'',
				'```css',
				$wrapper . ' .whim-promo__card::after {',
				'  opacity: 0;',
				'  transform: scaleX(0.4);',
				'  transition: opacity 460ms var(--whim-ease) 380ms,',
				'    transform 560ms var(--whim-ease) 380ms;',
				'}',
				'',
				$wrapper . '.is-lit .whim-promo__card::after { opacity: 0.9; transform: none }',
				'```',
				'',
				'Do not reach for `animation-timeline: view()`. It is the obvious tool for a',
				'scroll-driven entrance and it does not survive this site: an ad script writes an',
				'inline `overflow` onto `<body>`, which makes `<body>` a scroll container with',
				'nothing to scroll, so `view()` binds to it rather than the document and the',
				'animation sticks at its end state. The state classes above are driven from an',
				'observer that already exists, and transitions still run on the compositor.',
				'',
				'Respect `@media (prefers-reduced-motion: reduce)`: drop the movement, keep a short',
				'crossfade, and make sure the card still lands on screen.',
			]
		);
	}

	/**
	 * The remaining house rules.
	 *
	 * @param string $wrapper This promo's id selector.
	 *
	 * @return string
	 */
	protected static function rules( string $wrapper ): string {
		return implode(
			"\n",
			[
				'## House rules',
				'',
				'- **Scope every selector to `' . $wrapper . '`, written exactly like that.**',
				'  `' . Styles::ID_PLACEHOLDER . '` is a placeholder: the plugin replaces it with',
				'  the promo\'s own post id on output, so the same stylesheet can be pasted into',
				'  any promo and scopes itself. Do not substitute a number yourself. No bare class',
				'  selectors either — the stylesheet is inlined on a page that may carry several',
				'  promos, and an unscoped rule leaks onto all of them.',
				'- **Name every `@keyframes` `whim-kf-' . Styles::ID_PLACEHOLDER . '-something`.**',
				'  The same placeholder, replaced the same way, so two promos can carry different',
				'  edits of the same animation. `@keyframes` names are global otherwise and one',
				'  would silently overwrite the',
				'  other.',
				'- **No `@import`, no `url()` to a remote host, no web fonts.** The stylesheet is',
				'  inlined and a strict CSP applies. Inline any artwork as a `data:` URI.',
				'- **This loads before the site theme\'s CSS.** Bare element rules in the theme',
				'  (`button { inline-size: 100% }`, `a { border-block-end: 2px solid }`) would',
				'  otherwise win on order — the `' . $wrapper . '` id is what outranks them.',
				'- **Keep a visible focus ring** on every link, button and field, and do not put',
				'  one on `.whim-promo__card` itself: the card takes focus when a modal opens so',
				'  that Enter is not armed on a control nobody has read yet, and a ring there',
				'  would read as a selected control.',
				'- **The close button must keep a 44×44 hit area.** Position and colour it freely.',
				'- Use logical properties (`inline-size`, `padding-block`, `inset-inline`) and',
				'  `light-dark()` behind an `@supports` gate if you want a dark mode.',
			]
		);
	}

	/**
	 * A complete worked example: the template this promo currently uses.
	 *
	 * @param string $slug Style slug.
	 *
	 * @return string
	 */
	protected static function example( string $slug ): string {
		$template = Styles::to_placeholder( Styles::template( $slug ) );
		$label    = Styles::all()[ $slug ]['label'] ?? $slug;

		if ( '' === trim( $template ) ) {
			return "## A worked example\n\nNo bundled template was available to include.";
		}

		return implode(
			"\n",
			[
				'## A worked example',
				'',
				'This is the "' . $label . '" template in full, written the same way you should',
				'write yours. It covers every class and state above. Read it as the reference for',
				'completeness — then design something of your own rather than recolouring this.',
				'',
				'```css',
				$template,
				'```',
			]
		);
	}

	/**
	 * What to hand back.
	 *
	 * @param string $wrapper This promo's id selector.
	 *
	 * @return string
	 */
	protected static function deliverable( string $wrapper ): string {
		return implode(
			"\n",
			[
				'## What to hand back',
				'',
				'First an `html` block: a sample body for the editor. Include a heading, a line of',
				'prose with a link inside the sentence, a standalone link as the call to action, a',
				'standalone link with `class="whim-btn--google"`, and a link wrapping only an',
				'`<img>`. That way the editor can see every button shape at once.',
				'',
				'Then a `css` block: the complete stylesheet, every selector starting with',
				'`' . $wrapper . '`, covering',
				'',
				'- the card, its surface, type and ornament;',
				'- all three presentations — modal, top bar, bottom bar — and the inline case;',
				'- all four entry presets, plus the dismissing state;',
				'- every body shape and button variant listed above;',
				'- focus rings, reduced motion, and a dark mode if you want one.',
				'',
				'Say in one line what the design is going for. No other commentary — the two',
				'blocks get pasted straight into WordPress.',
			]
		);
	}
}
